name: cri-o
version: latest
summary: cri-o runtime
description: |-
  Lightweight container runtime for Kubernetes
license: Apache-2.0
grade: stable
confinement: classic
base: core20

parts:
  build-deps:
    plugin: nil
    override-build: |
      snap install go --classic --channel 1.20/stable
      snap refresh go --channel 1.20/stable
    build-packages:
      - pkg-config
      - libmnl-dev
      - libseccomp-dev
      - libgpgme-dev
      - libglib2.0-dev

  libnftnl:
    after: [build-deps]
    plugin: autotools
    source: https://www.netfilter.org/projects/libnftnl/files/libnftnl-1.1.8.tar.bz2

  iptables:
    after: [libnftnl]
    source: https://www.netfilter.org/projects/iptables/files/iptables-1.8.6.tar.bz2
    plugin: autotools
    build-environment:
      - LIBNFTNL_LIBS: $SNAPCRAFT_STAGE/usr/lib
    autotools-configure-parameters:
      - "--prefix=/usr"
      - "--exec-prefix=/"
      - "--disable-shared"
      - "--enable-static"
    prime:
      - -bin/iptables-xml

  runc:
    after: [iptables]
    plugin: make
    source: https://github.com/opencontainers/runc.git
    source-tag: v1.1.9
    make-parameters:
      - BUILDTAGS="seccomp apparmor"
      - EXTRA_LDFLAGS="-s -w"
      - static

  crio-o:
    after: [runc]
    plugin: make
    source: https://github.com/cri-o/cri-o.git
    source-tag: v1.28.0

  conmon:
    after: [build-deps]
    plugin: make
    source: https://github.com/containers/conmon.git
    source-tag: v2.1.8

apps:
  crio:
    command: usr/local/bin/crio
    daemon: simple
