name: Build and test cri-o snap

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Create snap package
    runs-on: ubuntu-20.04

    steps:
      - name: Checking out repo
        uses: actions/checkout@v3.3.0
      - name: Install lxd
        run: |
          sudo lxd init --auto
          sudo usermod --append --groups lxd $USER
          sg lxd -c 'lxc version'
      - name: Install snapcraft
        run: |
          sudo snap install snapcraft --classic
      - name: Install snapd from candidate
        run: |
          sudo snap refresh snapd --channel=latest/stable
      - name: Build snap
        run: |
          sg lxd -c 'snapcraft --use-lxd'
          sudo mv cri-o*.snap cri-o.snap
      - name: Uploading snap
        uses: actions/upload-artifact@v3
        with:
          name: cri-o.snap
          path: cri-o.snap
